# Generated by Django 3.2.3 on 2021-07-13 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_remove_house_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='preferredaccommodationtype',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='preferredage',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='preferredgender',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='preferredlocation',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='preferredmaxrent',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='preferredoccupation',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='preferredorientation',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='preferredreligion',
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferredgender', models.CharField(max_length=255, null=True)),
                ('preferredorientation', models.CharField(max_length=255, null=True)),
                ('preferredage', models.CharField(max_length=20, null=True)),
                ('preferredreligion', models.CharField(max_length=20, null=True)),
                ('preferredoccupation', models.CharField(max_length=255, null=True)),
                ('preferredlocation', models.CharField(max_length=255, null=True)),
                ('preferredmaxrent', models.IntegerField(null=True)),
                ('preferredaccommodationtype', models.CharField(max_length=255, null=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.userprofile')),
            ],
        ),
    ]
