# Generated by Django 3.2.3 on 2021-11-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_auto_20210713_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='preferredaccommodationtype1',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
