# Generated by Django 3.2.3 on 2021-11-29 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_userpreferences_preferredaccommodationtype1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreferences',
            name='preferredaccommodationtype1',
        ),
    ]
