# Generated by Django 3.2.3 on 2021-12-07 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0028_userprofile_housemate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='housemate_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
