# Generated by Django 3.2.3 on 2022-01-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_auto_20220103_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dateofbirth',
            field=models.DateField(default='00-00-0000', max_length=255),
        ),
    ]
