# Generated by Django 3.2.3 on 2022-03-21 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0035_alter_userprofile_dateofbirth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='accommodationtype',
        ),
        migrations.RemoveField(
            model_name='house',
            name='description',
        ),
        migrations.RemoveField(
            model_name='house',
            name='image',
        ),
        migrations.RemoveField(
            model_name='house',
            name='name',
        ),
        migrations.RemoveField(
            model_name='house',
            name='price',
        ),
        migrations.RemoveField(
            model_name='house',
            name='room',
        ),
        migrations.AddField(
            model_name='house',
            name='AdvertiserID',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='house',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='building',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='deposit',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='houseRules',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='monthlyRent',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='totalBathrooms',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='totalBedrooms',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='typeOfHost',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='typeOfListing',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='uploadphoto1',
            field=models.ImageField(blank=True, null=True, upload_to='houses/'),
        ),
        migrations.AddField(
            model_name='house',
            name='uploadphoto2',
            field=models.ImageField(blank=True, null=True, upload_to='houses/'),
        ),
        migrations.AddField(
            model_name='house',
            name='uploadphoto3',
            field=models.ImageField(blank=True, null=True, upload_to='houses/'),
        ),
        migrations.AddField(
            model_name='house',
            name='uploadphoto4',
            field=models.ImageField(blank=True, null=True, upload_to='houses/'),
        ),
        migrations.AddField(
            model_name='house',
            name='uploadphoto5',
            field=models.ImageField(blank=True, null=True, upload_to='houses/'),
        ),
        migrations.AlterField(
            model_name='house',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='houses/'),
        ),
    ]
