# Generated by Django 3.2.3 on 2022-03-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0036_auto_20220322_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='AdvertiserID',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
