# Generated by Django 3.2.3 on 2022-03-30 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0037_alter_house_advertiserid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='AdvertiserID',
            field=models.ForeignKey(max_length=500, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
