# Generated by Django 3.2.3 on 2022-03-30 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0038_alter_house_advertiserid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpreferences',
            old_name='preferredgender',
            new_name='preferredGender',
        ),
        migrations.RenameField(
            model_name='userpreferences',
            old_name='preferredoccupation',
            new_name='preferredOccupation',
        ),
        migrations.RenameField(
            model_name='userpreferences',
            old_name='preferredorientation',
            new_name='preferredOrientation',
        ),
        migrations.RenameField(
            model_name='userpreferences',
            old_name='preferredreligion',
            new_name='preferredReligion',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='preferredaccommodationtype',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='preferredage',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='preferredlocation',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='preferredmaxrent',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='user_id',
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='HouseID',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.house'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='preferredAge',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='preferredChildrenStatus',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='preferredPetStatus',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='preferredSmokingStatus',
            field=models.IntegerField(null=True),
        ),
    ]
