# Generated by Django 3.2.3 on 2022-04-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0042_auto_20220404_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='houseRules',
        ),
        migrations.AddField(
            model_name='house',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
