# Generated by Django 3.2.3 on 2022-04-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0045_auto_20220430_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='Psmoking',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
