# Generated by Django 3.2.3 on 2022-04-30 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0046_alter_userpreferences_psmoking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpreferences',
            old_name='PGender',
            new_name='Pgender',
        ),
    ]
