# Generated by Django 3.2.3 on 2022-05-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0048_alter_house_wifi_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='aircond_value',
            field=models.BooleanField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='furnished_value',
            field=models.BooleanField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='gym_value',
            field=models.BooleanField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='parking_value',
            field=models.BooleanField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='swimmingpool_value',
            field=models.BooleanField(blank=True, max_length=255, null=True),
        ),
    ]
