# Generated by Django 3.2.3 on 2022-05-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0050_auto_20220514_0052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='bio',
            new_name='aboutme',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='children',
            field=models.CharField(default='-', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='smoking',
            field=models.CharField(default='-', max_length=10, null=True),
        ),
    ]
