# Generated by Django 3.2.3 on 2022-07-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0054_auto_20220706_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='Page',
            field=models.CharField(default="I don't mind", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='Pchildren',
            field=models.CharField(default="I don't mind", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='Pgender',
            field=models.CharField(default="I don't mind", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='Poccupation',
            field=models.CharField(default="I don't mind", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='Ppet',
            field=models.CharField(default="I don't mind", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='Preligion',
            field=models.CharField(default="I don't mind", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='Psexorientation',
            field=models.CharField(default="I don't mind", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='Psmoking',
            field=models.CharField(default="I don't mind", max_length=255, null=True),
        ),
    ]
