# Generated by Django 3.2.3 on 2022-07-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0055_auto_20220706_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='typeOfRoom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
