# Generated by Django 3.2.3 on 2022-07-16 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0058_rename_state_house_building'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profilethumbnail',
        ),
    ]
