# Generated by Django 3.2.3 on 2022-07-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0059_auto_20220716_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='igAccount',
            field=models.CharField(default='-', max_length=255, null=True),
        ),
    ]
