# Generated by Django 3.2.3 on 2022-07-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0059_auto_20220716_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='HasRoom',
            field=models.CharField(default='Needs a place', max_length=255, null=True),
        ),
    ]
