# Generated by Django 3.2.3 on 2022-07-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0060_userprofile_igaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fbAccount',
            field=models.CharField(default='-', max_length=255, null=True),
        ),
    ]
