# Generated by Django 3.2.3 on 2022-07-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0060_alter_userprofile_hasroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='HasRoom',
            field=models.CharField(default='Needs A Place', max_length=255, null=True),
        ),
    ]
