# Generated by Django 3.2.3 on 2022-08-13 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0061_alter_userprofile_hasroom'),
        ('website', '0061_userprofile_fbaccount'),
    ]

    operations = [
    ]
