# Generated by Django 3.2.3 on 2022-08-18 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0062_merge_20220813_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='children',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='orientation',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='pet',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='religion',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='smoking',
        ),
    ]
