# Generated by Django 3.2.3 on 2022-08-18 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0064_auto_20220818_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='housecounter',
        ),
    ]
