# Generated by Django 3.2.3 on 2022-08-20 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0065_remove_userprofile_housecounter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='HasRoom',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='HasPet',
            field=models.CharField(default='Has No Pet', max_length=255, null=True),
        ),
    ]
