# Generated by Django 3.2.3 on 2022-08-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0066_auto_20220820_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='petcounter',
            field=models.IntegerField(default=0),
        ),
    ]
